#!/bin/csh -f

set count = 0

while ( 1 )
  set url = $<
  if ( $url == "" ) break
  echo $url
  set file = "xx-$count.${url:e}"
  echo "  $file"
  @ count = ( $count + 1 )
  curl -s -S -o "image-blogger/$file" "$url"
  sleep 1
end
